### PR TITLE
Faster LazyTensor mul!() for dense suboperators

### PR DESCRIPTION
**Pull request by amilsted**
This hooks up LazyTensor `mul!()`, specialized for dense suboperators, to BLAS (and hence enables multithreading for these ops as a side-effect). It uses TensorOperations.jl to handle the case of action on middle tensor factors (i.e. not the first or last subsystem).

These methods require allocating intermediate arrays in many cases (any time there is >1 suboperator, for example). Thes intermediates are cached using an LRUCache built in to TensorOperations.jl so that they can be reused for repeated applications of the same (or similar) operators.

There is some overhead that makes operations on very small Hilbert spaces a little slower than they were before, but this approach starts to win as the dimension grows. It works particularly nicely for dense suboperators on largish subsystems (say, dimension >~10) of even larger composite systems (dimensions > 100). In these cases, it is often several times faster than the existing mul!() implementation. It can also beat a SparseOperator in these cases (whereas before these changes, `sparse(LazyTensor(basis, i, dense(op)))` would often handily beat `LazyTensor(basis, i, dense(op))`).

I have been using LazyTensor for fast construction of dense subsystem operators with complicated time-dependence. These methods make this approach faster overall than constructing time-dependent sparse matrices, even when the mul!() operation itself has similar performance to the sparse-matrix version.

This approach should also work out of the box on GPU (I did some preliminary benchmarking, suggesting they can beat fully dense and sparse operations).

I will share some actual benchmarks soon.

PS: I spent some time getting the number of non-array allocations down. My `mul!()` still allocates a little more than the old method, but I think it's probably acceptable. Happy to find ways to reduce further.

### CODE REVIEW

**Comment by david-pl** [comment]
@amilsted thanks for the work on this PR!

After a brief look at the code I'd say everything's fine. Though I have to admit I never used TensorOperations.jl (or a lot of `LazyTensor`s for that matter), so I'm actually not sure if I can provide a sensible review here. However, I think you probably use `LazyTensor` more heavily than anybody else, so I'm inclined to just trust your changes and benchmarks here. @bastikr you wrote the original `gemm` methods for `LazyTensor`. Do you have any comments?

What I did notice is that there are quite a few new lines of code that aren't covered by the tests. Could you write more rigorous tests?

Also CI fails on 32-bit machines with `ERROR: LoadError: InexactError: trunc(Int32, 7291695104)`, but I'm not sure where this large integer comes from.

Finally, I'm a bit hesitant to add `TensorOperations` as dependency to QOBase.jl. The idea of QOBase.jl is to remain lightweight in terms of dependencies. However, `TensorOperations` depends on `CUDA`, which is quite heavy. Should we move this PR into QuantumOptics.jl instead? @PhilipVinc you usually have a good sense for when to add which dependencies. What do you think?

**Comment by amilsted** [comment]
Agreed that pulling in CUDA is unfortunate. It is possible to eliminate the TensorOperations.jl dependency by
1. implementing the contractions that currently use it with a `permutedims` and a matrix multiplication (this is essentially what TensorOperations.jl does in BLAS mode) and
2. doing the caching ourselves (using e.g. LRUCache.jl).

This should perform similarly to TensorOperations.jl in BLAS mode. One thing we lose by doing that is the "native" mode of TensorOperations.jl, which uses macros to compile contractions into for lops, which has the advantage of not requiring intermediate arrays. That said, it may not be so hard to reproduce the latter for our case too...

Perhaps we could do something like this in QuantumOpticsBase. If we still want to use TensorOperations, we could add this in QuantumOptics or a separate extension package.

**Comment by amilsted** [comment]
As for test coverage, I will try to improve that!

**Comment by amilsted** [comment]
@david-pl What do you think about using https://github.com/JuliaPackaging/Requires.jl to create a "soft" dependency on TensorOperations? This feels like the right thing to do, if it works. That way different implementations remain in the same package.

**Comment by PhilipVinc** [comment]
I would like to vote against adding CUDA as a dependency to QuantumOpticsBase.

The idea of `Base` package was to avoid introducing long loading times to packages depending on the core of QuantumOptics or trying to extend some common types.

On my MacBook laptop, where CUDA is essentially useless, CUDA adds 3.5s loading time against a current loading time of QuantumOpticsBase of 0.3s.
 
I'm also against introducing a dependency using Requires.jl because while that prevents precompilation.
Right now this will change little, because nobody tried to fix precompilation of QuantumOptics(base), requires would prevent such work in the future.
Precompiling QO.jl would make it even more appealing when compared to qutip, so I really, really vote against this.

Can we think of an alternative?

**Comment by david-pl** [comment]
> I would like to vote against adding CUDA as a dependency to QuantumOpticsBase.

Agreed.

I think the best option for now would be to push this whole PR to QuantumOptics. That way you can trade a longer load time for the extra speed you get here. It's not ideal, but the best I can think of right now.

The other reasonable suggestion by @amilsted is to create a separate extension package. But what would we put there besides just this functionality?

**Comment by PhilipVinc** [comment]
> I think the best option for now would be to push this whole PR to QuantumOptics. That way you can trade a longer load time for the extra speed you get here. It's not ideal, but the best I can think of right now.

Technically this is also wrong, though it's a valid stopgap solution: the way code caching (precompile) works is that only methods that type-pirate are not cached.

And this would be type pirating, because LazyTensor is defined in `QOBase.jl` and not in `QG.jl`.
Of course this is perfectly valid, but Julia internals don't know that...

Anyhow I still think it's a valid stopgap for now.

**Comment by amilsted** [comment]
> I'm also against introducing a dependency using Requires.jl because while that prevents precompilation.

I had not realized this and I agree that would be very unfortunate.

> I think the best option for now would be to push this whole PR to QuantumOptics. That way you can trade a longer load time for the extra speed you get here. It's not ideal, but the best I can think of right now.

Yeah, I'm fine with this option too.

> The other reasonable suggestion by @amilsted is to create a separate extension package. But what would we put there besides just this functionality?

Hmmm. Hook-up of SparseOperator `mul!()` to the built-in sparse matrix `mul!()` so that `MKLSparse.jl` works? Regardless, It would be a very piratey package... unless we split out the LazyTensor functionality completely, which seems drastic.

**Comment by amilsted** [comment]
I have reworked this to avoid depending on TensorOperations.jl (and hence CUDA.jl), settling on a permute-transpose-permute scheme for implementing operator action on tensor factors that are not the first or last subsystems.

An upside to this approach is that it also works for sparse operators, so I could completely remove the old code. It also reduces compilation time significantly, as TensorOperations was slowing this down quite a bit.

This adds an intermediate-result cache (based on the one in TensorOperations.jl, which I was previously using) to avoid excessive allocation. The intermediate cache could also be used to avoid extra allocations in LazyProduct.

TODO: Choose a sensible default cache size limit and add functions so that the user can clear the cache and set its max. size.

**Comment by amilsted** [comment]
Some timings for `operator * dense_operator` on a composite system with dimensions `(10, 8, 6)`:
```
combo		 new 	 newLS 	 old 	 oldLS 	 sparse 	(vs. fully-dense)
(1, 0, 0)	 5%	 21%	 52%	 49%	 26%
(0, 1, 0)	 11%	 23%	 38%	 38%	 22%
(1, 1, 0)	 17%	 44%	 376%	 378%	 131%
(0, 0, 1)	 13%	 24%	 32%	 32%	 19%
(1, 0, 1)	 17%	 45%	 271%	 267%	 97%
(0, 1, 1)	 26%	 53%	 206%	 206%	 77%
(1, 1, 1)	 33%	 77%	 2093%	 2116%	 673%
```
Here, the "combo" indicates which tensor factors re nontrivial in the operator. "LS" means a LazyTensor with SparseOperator components (LazySparse). Otherwise LazyTensors have dense components. The "LS" benchmarks here are not really representative of real-world usage, as the tensor factor operators are always generated with `randoperator()`.

The new code is always faster than the old on these tests. It is also always faster than a full sparse matrix.

Note: BLAS threading is off here, and benchmarks are performed using BenchmarkTools (median times) on my MBP on battery :)

**Comment by amilsted** [comment]
Here's how it looks when we use Fock number operators in the "LS" (and "sparser") cases:
```
combo		new	old	sparse	newLS	oldLS	sparser	(vs. fully-dense)
(1, 0, 0)	4%	95%	18%	5%	12%	4%
(0, 1, 0)	10%	61%	17%	9%	12%	4%
(1, 1, 0)	16%	660%	107%	17%	12%	4%
(0, 0, 1)	11%	37%	15%	12%	12%	4%
(1, 0, 1)	16%	398%	83%	19%	12%	5%
(0, 1, 1)	21%	264%	74%	24%	12%	4%
(1, 1, 1)	26%	3048%	853%	30%	12%	4%
```
Now the new code is slower than the old in the multi-factor LS cases, but both are still slower than a full sparse matrix approach ("sparser"). I could put the sparse parts of the old code back in for this purpose.

**Comment by amilsted** [comment]
Tidied things up and improved performance for smaller systems (avoid dynamic dispatch in cache lookups). Would like to add back the old methods for pure "lazy tensor product of sparse operators" operations, as they were much faster for this case. Not very urgent I think, because a full non-lazy sparse operator is usually still the fastest way to use sparsity here. Could consider just merging this for now. Thoughts? @david-pl @PhilipVinc

**Comment by amilsted** [comment]
QuantumOptics.jl tests also pass and the example notebooks run, so I will merge unless anyone objects.

**Pull request merged**
